import { useEffect, useState } from "react";
import { BarChart3, CheckCircle2, ClipboardPlus, Clock3, FileQuestion, Plus, Send, Users } from "lucide-react";
import { api } from "../api";
import type { Quiz, User } from "../types";

type DraftOption = { text: string; is_correct: boolean };
type DraftQuestion = { text: string; question_type: "mcq" | "msq" | "short"; marks: number; options: DraftOption[] };
const blankQuestion = (): DraftQuestion => ({ text: "", question_type: "mcq", marks: 1, options: [{ text: "", is_correct: true }, { text: "", is_correct: false }] });

export function ManagerDashboard({ user }: { user: User }) {
  const [tab, setTab] = useState<"overview" | "create" | "review">("overview");
  const [quizzes, setQuizzes] = useState<Quiz[]>([]); const [reviews, setReviews] = useState<any[]>([]);
  const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [draft, setDraft] = useState({ title: "", description: "", department: "Computer Science", semester: 1, duration_minutes: 30, questions: [blankQuestion()] });
  const refresh = () => { api<Quiz[]>("/quizzes").then(setQuizzes); api<any[]>("/attempts/review/pending").then(setReviews); };
  useEffect(refresh, []);
  async function createQuiz(e: React.FormEvent) { e.preventDefault(); setError(""); try { await api("/quizzes", { method: "POST", body: JSON.stringify(draft) }); setMessage("Quiz saved as draft."); setDraft({ ...draft, title: "", description: "", questions: [blankQuestion()] }); refresh(); setTab("overview"); } catch (e) { setError((e as Error).message); } }
  async function publish(id: number) { await api(`/quizzes/${id}/publish`, { method: "PATCH" }); setMessage("Quiz published successfully."); refresh(); }
  async function grade(answerId: number, max: number) { const marks = prompt(`Award marks (0-${max})`, String(max)); if (marks === null) return; const feedback = prompt("Feedback (optional)", "") || ""; try { await api(`/attempts/answers/${answerId}/grade`, { method: "PATCH", body: JSON.stringify({ awarded_marks: Number(marks), feedback }) }); refresh(); } catch (e) { setError((e as Error).message); } }
  function updateQuestion(index: number, values: Partial<DraftQuestion>) { const questions = [...draft.questions]; questions[index] = { ...questions[index], ...values }; if (values.question_type === "short") questions[index].options = []; if ((values.question_type === "mcq" || values.question_type === "msq") && !questions[index].options.length) questions[index].options = blankQuestion().options; setDraft({ ...draft, questions }); }
  return <div className="dashboard"><aside className="sidebar"><p>Workspace</p><button className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}><BarChart3 /> Overview</button><button className={tab === "create" ? "active" : ""} onClick={() => setTab("create")}><ClipboardPlus /> Create quiz</button><button className={tab === "review" ? "active" : ""} onClick={() => setTab("review")}><CheckCircle2 /> Review answers <i>{reviews.length}</i></button></aside>
    <section className="content"><div className="page-heading"><div><p className="eyebrow blue">{user.role} workspace</p><h1>{tab === "overview" ? "Quiz overview" : tab === "create" ? "Build a new quiz" : "Manual review"}</h1></div>{tab === "overview" && <button className="primary" onClick={() => setTab("create")}><Plus /> New quiz</button>}</div>
      {message && <div className="alert success">{message}</div>}{error && <div className="alert error">{error}</div>}
      {tab === "overview" && <><div className="stats"><div><span><FileQuestion /></span><p>Total quizzes</p><b>{quizzes.length}</b></div><div><span><Send /></span><p>Published</p><b>{quizzes.filter(q => q.status === "published").length}</b></div><div><span><Clock3 /></span><p>Awaiting review</p><b>{reviews.length}</b></div><div><span><Users /></span><p>Your role</p><b className="small-stat">{user.role}</b></div></div>
        <div className="panel"><div className="panel-title"><h2>Your quizzes</h2><span>{quizzes.length} total</span></div>{!quizzes.length ? <Empty text="No quizzes yet. Create your first assessment." /> : <div className="table-wrap"><table><thead><tr><th>Quiz</th><th>Audience</th><th>Duration</th><th>Questions</th><th>Status</th><th /></tr></thead><tbody>{quizzes.map(q => <tr key={q.id}><td><b>{q.title}</b><small>{q.description}</small></td><td>{q.department}<small>Semester {q.semester}</small></td><td>{q.duration_minutes} min</td><td>{q.questions.length}</td><td><span className={`badge ${q.status}`}>{q.status}</span></td><td>{q.status === "draft" && <button className="text-button" onClick={() => publish(q.id)}>Publish</button>}</td></tr>)}</tbody></table></div>}</div></>}
      {tab === "create" && <form className="builder" onSubmit={createQuiz}><div className="panel form-section"><h2>Quiz details</h2><div className="form-grid"><label>Title<input required value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} placeholder="e.g. Data Structures Mid Quiz" /></label><label>Department<input required value={draft.department} onChange={e => setDraft({ ...draft, department: e.target.value })} /></label><label>Semester<input required type="number" min="1" max="12" value={draft.semester} onChange={e => setDraft({ ...draft, semester: +e.target.value })} /></label><label>Time limit (minutes)<input required type="number" min="1" max="300" value={draft.duration_minutes} onChange={e => setDraft({ ...draft, duration_minutes: +e.target.value })} /></label><label className="full">Description<textarea value={draft.description} onChange={e => setDraft({ ...draft, description: e.target.value })} placeholder="Instructions or learning objective" /></label></div></div>
        {draft.questions.map((question, qi) => <div className="panel question-card" key={qi}><div className="question-head"><h2>Question {qi + 1}</h2>{draft.questions.length > 1 && <button type="button" className="danger-link" onClick={() => setDraft({ ...draft, questions: draft.questions.filter((_, i) => i !== qi) })}>Remove</button>}</div><div className="form-grid"><label className="full">Question<input required value={question.text} onChange={e => updateQuestion(qi, { text: e.target.value })} placeholder="Enter question text" /></label><label>Type<select value={question.question_type} onChange={e => updateQuestion(qi, { question_type: e.target.value as DraftQuestion["question_type"] })}><option value="mcq">MCQ — one correct</option><option value="msq">MSQ — multiple correct</option><option value="short">Short answer</option></select></label><label>Marks<input type="number" min="0.5" step="0.5" value={question.marks} onChange={e => updateQuestion(qi, { marks: +e.target.value })} /></label></div>
          {question.question_type !== "short" && <div className="options-editor"><p>Select the correct answer{question.question_type === "msq" ? "s" : ""}</p>{question.options.map((option, oi) => <div className="option-edit" key={oi}><input type={question.question_type === "mcq" ? "radio" : "checkbox"} name={`correct-${qi}`} checked={option.is_correct} onChange={e => { const options = question.options.map((o, i) => ({ ...o, is_correct: question.question_type === "mcq" ? i === oi : i === oi ? e.target.checked : o.is_correct })); updateQuestion(qi, { options }); }} /><input required value={option.text} onChange={e => { const options = [...question.options]; options[oi] = { ...options[oi], text: e.target.value }; updateQuestion(qi, { options }); }} placeholder={`Option ${oi + 1}`} />{question.options.length > 2 && <button type="button" onClick={() => updateQuestion(qi, { options: question.options.filter((_, i) => i !== oi) })}>×</button>}</div>)}<button type="button" className="text-button" onClick={() => updateQuestion(qi, { options: [...question.options, { text: "", is_correct: false }] })}>+ Add option</button></div>}</div>)}
        <div className="builder-actions"><button type="button" className="secondary" onClick={() => setDraft({ ...draft, questions: [...draft.questions, blankQuestion()] })}><Plus /> Add question</button><button className="primary">Save quiz draft</button></div></form>}
      {tab === "review" && <div className="review-list">{!reviews.length ? <Empty text="There are no short answers waiting for review." /> : reviews.map(review => <div className="panel review-card" key={review.id}><div className="panel-title"><div><h2>{review.quiz}</h2><span>Student: {review.student}</span></div><span>Attempt #{review.id}</span></div>{review.answers.map((answer: any) => <div className="review-answer" key={answer.answer_id}><p><b>{answer.question}</b> <span>{answer.max_marks} marks</span></p><blockquote>{answer.answer || "No answer provided"}</blockquote><button className="primary small" onClick={() => grade(answer.answer_id, answer.max_marks)}>Award marks</button></div>)}</div>)}</div>}
    </section></div>;
}
function Empty({ text }: { text: string }) { return <div className="empty"><FileQuestion /><h3>Nothing here yet</h3><p>{text}</p></div>; }

