import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, BookOpen, CheckCircle2, Clock3, Play, Send } from "lucide-react";
import { api } from "../api";
import type { Attempt, Quiz, User } from "../types";

type AnswerMap = Record<number, { selected_option_ids: number[]; text_answer: string }>;
export function StudentDashboard({ user }: { user: User }) {
  const [quizzes, setQuizzes] = useState<Quiz[]>([]); const [quiz, setQuiz] = useState<Quiz | null>(null); const [attempt, setAttempt] = useState<Attempt | null>(null); const [answers, setAnswers] = useState<AnswerMap>({}); const [seconds, setSeconds] = useState(0); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  useEffect(() => { api<Quiz[]>("/quizzes").then(setQuizzes).catch(e => setError(e.message)); }, []);
  const answerPayload = () => ({ answers: Object.entries(answers).map(([question_id, value]) => ({ question_id: +question_id, ...value })) });
  async function start(q: Quiz) { try { const next = await api<Attempt>(`/attempts/quizzes/${q.id}/start`, { method: "POST" }); setQuiz(q); setAttempt(next); setSeconds(Math.max(0, q.duration_minutes * 60 - Math.floor((Date.now() - new Date(next.started_at + "Z").getTime()) / 1000))); } catch (e) { setError((e as Error).message); } }
  async function submit() { if (!attempt) return; try { const result = await api<Attempt>(`/attempts/${attempt.id}/submit`, { method: "POST", body: JSON.stringify(answerPayload()) }); setAttempt(result); setNotice(result.status === "graded" ? "Your result is ready." : "Objective answers checked. Short answers are awaiting teacher review."); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { if (!attempt || attempt.status !== "in_progress") return; const timer = window.setInterval(() => setSeconds(s => { if (s <= 1) { window.clearInterval(timer); submit(); return 0; } return s - 1; }), 1000); const saver = window.setInterval(() => api(`/attempts/${attempt.id}/answers`, { method: "PUT", body: JSON.stringify(answerPayload()) }).catch(() => {}), 30000); return () => { clearInterval(timer); clearInterval(saver); }; }, [attempt?.id, attempt?.status, answers]);
  useEffect(() => { if (!attempt || attempt.status !== "in_progress") return; const visibility = async () => { if (document.visibilityState !== "hidden") return; try { const result = await api<Attempt>(`/attempts/${attempt.id}/tab-switch`, { method: "POST" }); if (result.tab_switches >= 2) { await submit(); } else { setNotice("Warning: leaving this quiz again will submit your attempt automatically."); } } catch {} }; document.addEventListener("visibilitychange", visibility); return () => document.removeEventListener("visibilitychange", visibility); }, [attempt?.id, attempt?.status, answers]);
  const answered = useMemo(() => Object.values(answers).filter(a => a.text_answer || a.selected_option_ids.length).length, [answers]);
  if (quiz && attempt) {
    if (attempt.status !== "in_progress") return <Result attempt={attempt} quiz={quiz} notice={notice} onBack={() => { setQuiz(null); setAttempt(null); }} />;
    return <div className="attempt-page"><div className="attempt-header"><div><p className="eyebrow blue">Active assessment</p><h1>{quiz.title}</h1><span>{quiz.department} · Semester {quiz.semester}</span></div><div className={`timer ${seconds < 60 ? "danger" : ""}`}><Clock3 /><div><small>Time remaining</small><b>{String(Math.floor(seconds / 60)).padStart(2, "0")}:{String(seconds % 60).padStart(2, "0")}</b></div></div></div>{notice && <div className="alert warning"><AlertTriangle /> {notice}</div>}<div className="progress-row"><span>{answered} of {quiz.questions.length} answered</span><progress max={quiz.questions.length} value={answered} /></div>
      <div className="attempt-layout"><nav className="question-nav"><b>Questions</b><div>{quiz.questions.map((q, i) => <a key={q.id} href={`#question-${q.id}`} className={answers[q.id]?.text_answer || answers[q.id]?.selected_option_ids.length ? "done" : ""}>{i + 1}</a>)}</div><p><span className="dot done" /> Answered</p><p><span className="dot" /> Not answered</p></nav><section className="questions-list">{quiz.questions.map((q, i) => <article className="panel attempt-question" id={`question-${q.id}`} key={q.id}><div className="question-meta"><span>Question {i + 1}</span><span>{q.marks} marks · {q.question_type.toUpperCase()}</span></div><h2>{q.text}</h2>{q.question_type === "short" ? <textarea rows={5} placeholder="Write your answer here…" value={answers[q.id]?.text_answer || ""} onChange={e => setAnswers({ ...answers, [q.id]: { selected_option_ids: [], text_answer: e.target.value } })} /> : <div className="answer-options">{q.options.map(option => { const selected = answers[q.id]?.selected_option_ids || []; return <label className={selected.includes(option.id) ? "selected" : ""} key={option.id}><input type={q.question_type === "mcq" ? "radio" : "checkbox"} name={`question-${q.id}`} checked={selected.includes(option.id)} onChange={e => { const ids = q.question_type === "mcq" ? [option.id] : e.target.checked ? [...selected, option.id] : selected.filter(id => id !== option.id); setAnswers({ ...answers, [q.id]: { selected_option_ids: ids, text_answer: "" } }); }} /><span>{option.text}</span></label>})}</div>}</article>)}<button className="primary submit-button" onClick={() => { if (confirm("Submit your quiz? You cannot change answers afterwards.")) submit(); }}><Send /> Submit quiz</button></section></div></div>;
  }
  return <div className="student-home"><div className="student-welcome"><p className="eyebrow">Student dashboard</p><h1>Welcome back, {user.name.split(" ")[0]}.</h1><p>Your published quizzes for <b>{user.department}</b>, semester <b>{user.semester}</b>.</p></div>{error && <div className="alert error">{error}</div>}<div className="quiz-grid">{quizzes.length ? quizzes.map(q => <article className="quiz-tile" key={q.id}><div className="tile-icon"><BookOpen /></div><span className="badge published">Available</span><h2>{q.title}</h2><p>{q.description || "Complete this assessment within the assigned time."}</p><div className="tile-meta"><span><Clock3 /> {q.duration_minutes} minutes</span><span>{q.questions.length} questions</span></div><button className="primary wide" onClick={() => start(q)}><Play /> Start quiz</button></article>) : <div className="empty panel"><BookOpen /><h3>No quiz available</h3><p>Your teacher has not published a quiz for your department and semester.</p></div>}</div></div>;
}
function Result({ attempt, quiz, notice, onBack }: { attempt: Attempt; quiz: Quiz; notice: string; onBack: () => void }) { const percent = attempt.total_marks ? Math.round((attempt.final_score / attempt.total_marks) * 100) : 0; return <div className="result-page"><div className="result-card"><div className="result-icon"><CheckCircle2 /></div><p className="eyebrow blue">Quiz submitted</p><h1>{quiz.title}</h1><p>{notice}</p><div className="score-ring" style={{ "--score": `${percent * 3.6}deg` } as React.CSSProperties}><div><b>{attempt.final_score}</b><span>out of {attempt.total_marks}</span></div></div><div className="result-breakdown"><span>Objective score <b>{attempt.objective_score}</b></span><span>Manual score <b>{attempt.status === "awaiting_review" ? "Pending" : attempt.manual_score}</b></span><span>Status <b>{attempt.status === "graded" ? "Completed" : "Teacher review"}</b></span></div>{attempt.status === "awaiting_review" && <div className="alert warning">Your complete result will be emailed after the teacher checks your short answers.</div>}<button className="secondary" onClick={onBack}>Back to dashboard</button></div></div>; }

