<?php require_once 'includes/functions.php';require_login();if(is_staff())redirect('admin/index.php');
$pdo=db();$s=$pdo->prepare("SELECT COUNT(*) attempts,COALESCE(ROUND(AVG(percentage),1),0) average,COALESCE(MAX(percentage),0) best FROM attempts WHERE user_id=?");$s->execute([user()['id']]);$stats=$s->fetch();
$s=$pdo->prepare("SELECT a.id,a.score,a.total_questions,a.percentage,a.completed_at,q.title FROM attempts a JOIN quizzes q ON q.id=a.quiz_id WHERE a.user_id=? ORDER BY a.completed_at DESC LIMIT 5");$s->execute([user()['id']]);$recent=$s->fetchAll();
$quizzes=$pdo->query("SELECT q.id,q.title,q.time_limit_minutes,c.name category,(SELECT COUNT(*) FROM questions WHERE quiz_id=q.id) question_count FROM quizzes q JOIN categories c ON c.id=q.category_id WHERE q.is_published=1 ORDER BY q.created_at DESC LIMIT 6")->fetchAll();
$pageTitle='Student Dashboard';require 'includes/header.php';?>
<h1>Welcome, <?=e(user()['name'])?></h1><div class="grid"><div class="card"><span class="muted">Attempts</span><div class="stats"><?=$stats['attempts']?></div></div><div class="card"><span class="muted">Average</span><div class="stats"><?=$stats['average']?>%</div></div><div class="card"><span class="muted">Best Score</span><div class="stats"><?=$stats['best']?>%</div></div></div>
<h2>Available Quizzes</h2><div class="grid"><?php foreach($quizzes as $q):?><article class="card"><span class="badge"><?=e($q['category'])?></span><h3><?=e($q['title'])?></h3><p><?=$q['question_count']?> questions · <?=$q['time_limit_minutes']?> minutes</p><a class="button" href="instructions.php?id=<?=$q['id']?>">View Quiz</a></article><?php endforeach;?><?php if(!$quizzes):?><p>No published quizzes yet.</p><?php endif;?></div>
<h2>Recent Results</h2><div class="table-wrap"><table><tr><th>Quiz</th><th>Score</th><th>Percentage</th><th>Date</th><th></th></tr><?php foreach($recent as $r):?><tr><td><?=e($r['title'])?></td><td><?=$r['score']?> / <?=$r['total_questions']?></td><td><?=$r['percentage']?>%</td><td><?=date('d M Y',strtotime($r['completed_at']))?></td><td><a href="result.php?id=<?=$r['id']?>">View</a></td></tr><?php endforeach;?></table><?php if(!$recent):?><p>You have not attempted a quiz yet.</p><?php endif;?></div>
<?php require 'includes/footer.php';?>
