<?php
require_once 'includes/functions.php';require_login();$quizId=(int)($_GET['id']??$_POST['quiz_id']??0);$pdo=db();
$s=$pdo->prepare('SELECT * FROM quizzes WHERE id=? AND is_published=1');$s->execute([$quizId]);$quiz=$s->fetch();if(!$quiz){http_response_code(404);exit('Quiz not found.');}
$s=$pdo->prepare('SELECT COUNT(*) FROM attempts WHERE user_id=? AND quiz_id=?');$s->execute([user()['id'],$quizId]);if((int)$s->fetchColumn()>0&&!$quiz['allow_retakes']){flash('error','Retake is not allowed for this quiz.');redirect("instructions.php?id=$quizId");}
$s=$pdo->prepare('SELECT q.id,q.question_text,o.id option_id,o.option_text FROM questions q JOIN options o ON o.question_id=q.id WHERE q.quiz_id=? ORDER BY q.id,o.id');$s->execute([$quizId]);$rows=$s->fetchAll();$questions=[];foreach($rows as $r){$questions[$r['id']]['text']=$r['question_text'];$questions[$r['id']]['options'][]=['id'=>$r['option_id'],'text'=>$r['option_text']];}if(!$questions)exit('This quiz has no questions.');
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$answers=$_POST['answers']??[];$pdo->beginTransaction();try{$correct=0;$details=[];
 foreach($questions as $qid=>$question){$selected=(int)($answers[$qid]??0);$x=$pdo->prepare('SELECT id,is_correct FROM options WHERE question_id=?');$x->execute([$qid]);$opts=$x->fetchAll();$correctId=0;foreach($opts as $o)if($o['is_correct'])$correctId=(int)$o['id'];$isCorrect=$selected>0&&$selected===$correctId;if($isCorrect)$correct++;$details[]=[$qid,$selected?:null,$isCorrect];}
 $total=count($questions);$percent=round($correct/$total*100,2);$x=$pdo->prepare('INSERT INTO attempts(user_id,quiz_id,score,total_questions,percentage) VALUES(?,?,?,?,?)');$x->execute([user()['id'],$quizId,$correct,$total,$percent]);$attemptId=(int)$pdo->lastInsertId();$x=$pdo->prepare('INSERT INTO attempt_answers(attempt_id,question_id,selected_option_id,is_correct) VALUES(?,?,?,?)');foreach($details as $d)$x->execute([$attemptId,$d[0],$d[1],$d[2]]);$pdo->commit();redirect("result.php?id=$attemptId");}catch(Throwable $e){$pdo->rollBack();throw $e;}}
$pageTitle='Attempt Quiz';require 'includes/header.php';?>
<form id="quiz-form" class="form-card wide" method="post" data-seconds="<?=$quiz['time_limit_minutes']*60?>"><?=csrf_field()?><input type="hidden" name="quiz_id" value="<?=$quizId?>"><div class="quiz-top"><div><h1><?=e($quiz['title'])?></h1><span id="question-number"></span></div><strong>Time: <span id="timer"></span></strong></div><div class="progress"><span></span></div>
<?php $n=0;foreach($questions as $qid=>$q):$n++;?><section class="question"><h2><?=$n?>. <?=e($q['text'])?></h2><?php foreach($q['options'] as $o):?><label class="option"><input type="radio" name="answers[<?=$qid?>]" value="<?=$o['id']?>"> <?=e($o['text'])?></label><?php endforeach;?></section><?php endforeach;?><div class="actions"><button type="button" class="button secondary" id="prev">Previous</button><button type="button" id="next">Next</button><button type="submit" id="submit-quiz" hidden>Submit Quiz</button></div></form>
<?php require 'includes/footer.php';?>
