<?php require_once '../includes/functions.php';require_staff();$pdo=db();$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=post('action');$id=(int)($_POST['id']??0);[$access,$accessParams]=quiz_access_sql();
 if($action==='create'){$title=post('title');$category=(int)($_POST['category_id']??0);$time=max(1,(int)($_POST['time_limit']??10));if(!$title||!$category)$errors[]='Title and category are required.';else{$s=$pdo->prepare('INSERT INTO quizzes(category_id,title,description,time_limit_minutes,allow_retakes,is_published,created_by) VALUES(?,?,?,?,?,?,?)');$s->execute([$category,$title,post('description'),$time,isset($_POST['allow_retakes']),0,user()['id']]);flash('success','Quiz created. Add questions, then publish it.');redirect('questions.php?quiz_id='.$pdo->lastInsertId());}}
 if($action==='toggle'){$s=$pdo->prepare("UPDATE quizzes q SET is_published=NOT is_published WHERE q.id=? AND $access");$s->execute(array_merge([$id],$accessParams));flash('success','Quiz status updated.');redirect('quizzes.php');}
 if($action==='delete'){$s=$pdo->prepare("DELETE q FROM quizzes q WHERE q.id=? AND $access");$s->execute(array_merge([$id],$accessParams));flash('success','Quiz and its questions deleted.');redirect('quizzes.php');}}
$cats=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll();[$access,$params]=quiz_access_sql();$s=$pdo->prepare("SELECT q.*,c.name category,(SELECT COUNT(*) FROM questions WHERE quiz_id=q.id) questions FROM quizzes q JOIN categories c ON c.id=q.category_id WHERE $access ORDER BY q.created_at DESC");$s->execute($params);$quizzes=$s->fetchAll();$pageTitle='Manage Quizzes';require '../includes/header.php';?>
<div class="split"><form class="form-card wide" method="post"><h1>Create Quiz</h1><?php foreach($errors as $x):?><p class="error"><?=e($x)?></p><?php endforeach;?><?=csrf_field()?><input type="hidden" name="action" value="create"><label>Quiz Title</label><input name="title" required><label>Category</label><select name="category_id" required><option value="">Select</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select><label>Description</label><textarea name="description"></textarea><label>Time Limit (minutes)</label><input type="number" name="time_limit" min="1" value="10" required><label class="option"><input type="checkbox" name="allow_retakes" checked> Allow students to retake</label><button>Create and Add Questions</button></form><div class="card"><h2>Need a faster option?</h2><p>Give AI a topic and it will prepare a complete draft quiz. Review it before publishing.</p><a class="button secondary" href="ai_generate.php">Generate with AI</a></div></div>
<h2>All Quizzes</h2><div class="table-wrap"><table><tr><th>Quiz</th><th>Category</th><th>Questions</th><th>Status</th><th>Actions</th></tr><?php foreach($quizzes as $q):?><tr><td><?=e($q['title'])?></td><td><?=e($q['category'])?></td><td><?=$q['questions']?></td><td><?=$q['is_published']?'Published':'Draft'?></td><td><a href="questions.php?quiz_id=<?=$q['id']?>">Questions</a> · <form class="inline" method="post"><?=csrf_field()?><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$q['id']?>"><button class="button small secondary"><?=$q['is_published']?'Unpublish':'Publish'?></button></form> <form class="inline" method="post"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$q['id']?>"><button class="button small danger" data-confirm="Delete this quiz and all results?">Delete</button></form></td></tr><?php endforeach;?></table></div>
<?php require '../includes/footer.php';?>
